[package]
name = "assertable_core"
version = "0.1.0"
authors = ["Alexandra Ã˜stermark <alex.cramt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
